# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml



trigger:
- master

pool:
  vmImage: 'ubuntu-20.04'



container: mcr.microsoft.com/playwright:focal


steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.9'
    addToPath: true
    architecture: 'x64'


- script: |
    pip install -r requirements.txt
    pip install pytest pytest-azurepipelines
    pip install pytest-cov
    pytest --junitxml=junit/test-results.xml
  displayName: 'pytest'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
